# Running Prettier on staged files
'*.{ts, tsx, jsx, js, json, md, yaml, cts, cjs}':
  - 'prettier --write'

# Running ESLint on staged files
'*.{ts, tsx, jsx, js}':
  - 'eslint  --fix'

# Re-stage all updated/changed files from Prettier and/or ESLint
'*.{ts, tsx, jsx, js, json, md, yaml, cts, cjs, yml}':
  - 'git add'
