[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = '''
  default-src 'self';
  frame-src 'self' https://www.google.com https://www.gstatic.com;
  script-src 'self' https://www.google.com https://www.gstatic.com 'unsafe-inline' 'unsafe-eval';
  style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
  font-src 'self' https://fonts.gstatic.com;
  connect-src 'self' https://www.google.com https://www.gstatic.com https://itihaas-api.onrender.com;
  media-src 'self' https://en-audio.howtopronounce.com;
'''
