[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "frame-ancestors 'self'; frame-src 'self' https://www.google.com/ https://www.gstatic.com/; script-src 'self' https://www.google.com/ https://www.gstatic.com/ 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
